from __future__ import annotations

import subprocess
import time
from pathlib import Path
from typing import Any

import psycopg2.sql as sql

from .db import Db
from .params import ParameterSpec, repair_config


class ConfigApplier:
    def __init__(self, target_db: Db, specs: list[ParameterSpec], apply_settings: dict[str, Any]):
        self.target_db = target_db
        self.specs_by_name = {s.name: s for s in specs}
        self.settings = apply_settings

    def apply(self, config: dict[str, Any]) -> None:
        config = repair_config(config)
        mode = self.settings.get("mode", "alter_system")
        if mode in ("none", "off", "disabled"):
            return
        if mode == "alter_system":
            need_restart = self.apply_alter_system(config)
        elif mode == "file":
            need_restart = self.apply_file(config)
        else:
            raise ValueError(f"Неизвестный apply.mode: {mode}")

        restart_cmd = self.settings.get("restart_cmd")
        if need_restart and restart_cmd:
            subprocess.run(restart_cmd, shell=True, check=True)
        else:
            self.reload_conf()

        settle_seconds = int(self.settings.get("settle_seconds", 0) or 0)
        if settle_seconds > 0:
            time.sleep(settle_seconds)

    def apply_alter_system(self, config: dict[str, Any]) -> bool:
        need_restart = False
        with self.target_db.conn() as conn:
            conn.autocommit = True
            with conn.cursor() as cur:
                for name, value in config.items():
                    spec = self.specs_by_name.get(name)
                    if not spec:
                        continue
                    formatted = spec.format_for_postgres(value)
                    cur.execute(
                        sql.SQL("ALTER SYSTEM SET {} = %s").format(sql.Identifier(name)),
                        (formatted,),
                    )
                    need_restart = need_restart or spec.restart
                cur.execute("SELECT pg_reload_conf()")
        return need_restart

    def apply_file(self, config: dict[str, Any]) -> bool:
        need_restart = False
        output_path = Path(self.settings.get("conf_output_path", "./postgresql.auto.tuner.conf"))
        lines = ["# generated by tsdb-tuner; do not edit manually"]
        for name, value in config.items():
            spec = self.specs_by_name.get(name)
            if not spec:
                continue
            formatted = spec.format_for_postgres(value)
            escaped = formatted.replace("'", "''")
            lines.append(f"{name} = '{escaped}'")
            need_restart = need_restart or spec.restart
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return need_restart

    def reload_conf(self) -> None:
        try:
            with self.target_db.conn() as conn:
                with conn.cursor() as cur:
                    cur.execute("SELECT pg_reload_conf()")
        except Exception:
            pass

    def snapshot_settings(self, names: list[str]) -> dict[str, str | None]:
        if not names:
            return {}
        with self.target_db.conn() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT name, setting, unit FROM pg_settings WHERE name = ANY(%s)", (names,))
                rows = cur.fetchall()
        return {name: f"{setting}{unit or ''}" for name, setting, unit in rows}
